SER-841 Prevent click word from hanging
serenadeai/chrome pull request #22
Opened 2021-05-07 22:28 UTC by sam-dixon

Catches error if "click <word>" command produces an invalid XPath expression.

2021-05-18 00:28 UTC, MattWiethoff requested changes
Spoke offline about this. Looks like we need to be escaping the search string / not passing in symbols.

2021-05-18 21:23 UTC, sam-dixon commented
It turns out there were two separate issues with characters that needed to be escaped:
* the regex wouldn't match any phrases that contained regex special characters (this is why "click dot" failed)
* the `document.evaluate` call would hang for contractions, since adding any path with the "'" character would make the XPath expression invalid

Both of these should be fixed

2021-05-20 20:50 UTC, MattWiethoff requested changes

2021-05-20 20:50 UTC, MattWiethoff commented on src/content/overlay.ts
> +          .replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
```suggestion
          // See https://stackoverflow.com/questions/3561493/is-there-a-regexp-escape-function-in-javascript/3561711#3561711
          .replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
```

2021-05-20 20:50 UTC, MattWiethoff commented on src/content/overlay.ts
> +        `.//*[not(self::script)][not(self::noscript)][not(self::title)][not(self::meta)][not(self::svg)][not(self::style)][text()[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnop
Nice find with both of these. While still rare, it looks like `"` can still cause issues.

@tmacwill do you have any view on this? Looks like it's hard to escape xpath. Maybe there's a better pattern here? Perhaps not trying to do all of this complicated logic in `document.evaluate`?

2021-05-30 19:26 UTC, sam-dixon commented
Just added a utility function to escape the quotes when building the XPath expression.

2021-06-08 23:02 UTC, MattWiethoff approved these changes
Great, thanks!

2021-06-08 23:06 UTC, merged